# Generated by Django 4.0.2 on 2022-02-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psico_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='name',
        ),
        migrations.AddField(
            model_name='seccion',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
