# Generated by Django 4.0.2 on 2022-02-12 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psico_api', '0002_remove_seccion_name_seccion_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='description',
            new_name='tipo',
        ),
    ]
