# Generated by Django 4.0.2 on 2022-02-13 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psico_api', '0004_remove_choice_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seccion',
            new_name='Section',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='seccion',
            new_name='section',
        ),
    ]
